kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}
rules:
  {{ range .Values.clusterRoleRules }}
  - apiGroups: ["{{ join "\",\"" .apiGroups }}"]
    resources: ["{{ join "\",\"" .resources }}"]
    verbs: ["{{ join "\",\"" .verbs }}"]
    {{ if .resourceNames }}resourceNames: ["{{ join "\",\"" .resourceNames }}"]{{ end }}
  {{ end }}
