kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}
rules:
  {{ range .Values.clusterRoleRules }}
  - apiGroups: {{ .apiGroups }}
    resources: {{ .resources }}
    verbs: {{ .verbs }}
    resourceNames: {{ .resourceNames }}
  {{ end }}
