kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: {{ default "kube-system" .Release.Namespace }}
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: {{ .Values.flannelConfig.cniConf | toJson | quote }}
  net-conf.json: {{ .Values.flannelConfig.netConf | toJson | quote }}
